language: python
dist: trusty
python:
  - "3.5"
addons:
  apt:
    packages:
    - enchant

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install twine
  - pip install flake8

script:
  - flake8 . --ignore=E722

after_success:
  - coverage report
  - codecov

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
